classDiagram
 class Big {
  +int field0
  +int field1
  +int field2
  +int field3
  +int field4
  +int field5
  +int field6
  +int field7
  +int field8
  +int field9
  +int field10
  +int field11
  +method0() void
  +method1() void
  +method2() void
  +method3() void
  +method4() void
  +method5() void
  +method6() void
  +method7() void
  +method8() void
  +method9() void
  +method10() void
  +method11() void
 }
 Big <|-- Small
 Big *-- Part
 Big o-- Agg
 Big ..> Dep
