erDiagram
 HUB ||--o{ SPOKE0 : links
 HUB ||--o{ SPOKE1 : links
 HUB ||--o{ SPOKE2 : links
 HUB ||--o{ SPOKE3 : links
 HUB ||--o{ SPOKE4 : links
 HUB ||--o{ SPOKE5 : links
 HUB ||--o{ SPOKE6 : links
 HUB ||--o{ SPOKE7 : links
 HUB ||--o{ SPOKE8 : links
 HUB ||--o{ SPOKE9 : links
