sequenceDiagram
 autonumber
 A->>B: request 0
 B-->>A: response 0
 A->>B: request 1
 B-->>A: response 1
 A->>B: request 2
 B-->>A: response 2
 A->>B: request 3
 B-->>A: response 3
 A->>B: request 4
 B-->>A: response 4
 A->>B: request 5
 B-->>A: response 5
 A->>B: request 6
 B-->>A: response 6
 A->>B: request 7
 B-->>A: response 7
 A->>B: request 8
 B-->>A: response 8
 A->>B: request 9
 B-->>A: response 9
 A->>B: request 10
 B-->>A: response 10
 A->>B: request 11
 B-->>A: response 11
 A->>B: request 12
 B-->>A: response 12
 A->>B: request 13
 B-->>A: response 13
 A->>B: request 14
 B-->>A: response 14
 A->>B: request 15
 B-->>A: response 15
 A->>B: request 16
 B-->>A: response 16
 A->>B: request 17
 B-->>A: response 17
 A->>B: request 18
 B-->>A: response 18
 A->>B: request 19
 B-->>A: response 19
 A->>B: request 20
 B-->>A: response 20
