stateDiagram-v2
 [*] --> Hub
 Hub --> S0: evt0
 Hub --> S1: evt1
 Hub --> S2: evt2
 Hub --> S3: evt3
 Hub --> S4: evt4
 Hub --> S5: evt5
 Hub --> S6: evt6
 Hub --> S7: evt7
 Hub --> S8: evt8
 Hub --> S9: evt9
 Hub --> S10: evt10
 Hub --> S11: evt11
 Hub --> S12: evt12
 Hub --> S13: evt13
 Hub --> S14: evt14
 Hub --> S15: evt15
